import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import {
  GiAutoRepair,
  GiVacuumCleaner,
  GiWashingMachine,
} from "react-icons/gi";
import { BiCabinet } from "react-icons/bi";
import { BsFillTreeFill, BsSnow } from "react-icons/bs";

const categories = [
  {
    name: "Cleaning",
    icon: <GiVacuumCleaner className="text-5xl text-primary-100" />,
    label: "Cleaning",
  },
  {
    name: "Indoors",
    icon: <BiCabinet className="text-5xl text-primary-100" />,
    label: "Indoors",
  },
  {
    name: "Install",
    icon: <GiWashingMachine className="text-5xl text-primary-100" />,
    label: "Install",
  },
  {
    name: "Outdoors",
    icon: <BsFillTreeFill className="text-5xl text-primary-100" />,
    label: "Outdoors",
  },
  {
    name: "Repair",
    icon: <GiAutoRepair className="text-5xl text-primary-100" />,
    label: "Repair",
  },
  {
    name: "Seasonal",
    icon: <BsSnow className="text-5xl text-primary-100" />,
    label: "Seasonal",
  },
];

const ServiceCategory = ({ icon, label }) => {
  return (
    <div className="bg-white rounded-lg flex flex-col justify-center items-center w-36 py-8 shadow-md hover:shadow-lg cursor-pointer transform transition duration-500 hover:scale-110">
      {icon}
      <div className="pt-6">{label}</div>
    </div>
  );
};

// apply css styles on one class but effects should be on another class as well

const ServiceType = () => {
  return (
    <section className="flex justify-center w-[275px] transform transition duration-500 hover:-translate-y-2">
      <div className="rounded-lg bg-white max-w-sm">
        <Link href="#">
          <a>
            <div className="relative">
              <Image
                className="rounded-lg"
                src="https://d2zdpiztbgorvt.cloudfront.net/region1/us/173102/biz_photo/a0c65af40bdf488c9ed98b92bd6780-roy-master-barber-biz-photo-c89d068112214cb2a81d03576c3b58-booksy.jpeg?size=640x427"
                alt=""
                width={275}
                height={180}
              />

              <div className="w-full absolute bottom-1 rounded-bl-lg rounded-br-lg right-0 text-white text-right p-4 bg-gradient-to-t from-zinc-900 to-transparent">
                <div className="font-bold text-lg">Appliance Repair</div>
              </div>
            </div>
          </a>
        </Link>
      </div>
    </section>
  );
};

export default function Services() {
  return (
    <>
      <Head>
        <title>TechLance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="p-4 bg-gray-100 flex justify-center">
          <div className="w-1/2 flex justify-between">
            {categories.map((category) => {
              return (
                <ServiceCategory
                  key={category.label}
                  icon={category.icon}
                  label={category.label}
                />
              );
            })}
          </div>
        </section>

        <section className="border-2 border-black">
          <ServiceType />
        </section>
      </main>
    </>
  );
}
