import Head from "next/head";
import Image from "next/image";

import {
  GiAutoRepair,
  GiVacuumCleaner,
  GiWashingMachine,
} from "react-icons/gi";
import { BiCabinet } from "react-icons/bi";
import { BsFillTreeFill, BsSnow } from "react-icons/bs";

const categories = [
  {
    name: "Cleaning",
    icon: <GiVacuumCleaner className="text-5xl text-primary-100" />,
    label: "Cleaning",
  },
  {
    name: "Indoors",
    icon: <BiCabinet className="text-5xl text-primary-100" />,
    label: "Indoors",
  },
  {
    name: "Install",
    icon: <GiWashingMachine className="text-5xl text-primary-100" />,
    label: "Install",
  },
  {
    name: "Outdoors",
    icon: <BsFillTreeFill className="text-5xl text-primary-100" />,
    label: "Outdoors",
  },
  {
    name: "Repair",
    icon: <GiAutoRepair className="text-5xl text-primary-100" />,
    label: "Repair",
  },
  {
    name: "Seasonal",
    icon: <BsSnow className="text-5xl text-primary-100" />,
    label: "Seasonal",
  },
];

const ServiceCategory = ({ icon, label }) => {
  return (
    <div className="bg-white rounded-lg flex flex-col justify-center items-center w-36 py-8 shadow-md hover:shadow-lg cursor-pointer">
      {icon}
      <div className="pt-6">{label}</div>
    </div>
  );
};

export default function Services() {
  return (
    <>
      <Head>
        <title>TechLance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      all services list here
      <main className="p-4 bg-gray-100 flex justify-center">
        <div className="w-1/2 flex justify-between">
          {categories.map((category) => {
            return (
              <ServiceCategory
                key={category.label}
                icon={category.icon}
                label={category.label}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}
