import React from "react";
import Head from "next/head";
import Image from "next/image";

import {
  ClientHero,
  ClientServiceCategories,
  ClientRecommendations,
  ClientAboutSectionOne,
  ClientAboutSectionTwo,
  ClientAboutSectionThree,
  Footer,
} from "@/components";
import { Services, Bookings, Reminders } from "@/assets";

export default function Home() {
  return (
    <>
      <Head>
        <title>TechLance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ClientHero />
        <ClientRecommendations />
        <ClientServiceCategories />
        <ClientAboutSectionOne />
        <ClientAboutSectionTwo />
        <ClientAboutSectionThree />
      </main>

      <Footer />
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {},
  };
}
