import Head from "next/head";

import {
  ClientHero,
  ClientHomeCategories,
  ClientRecommendations,
  ClientAboutSectionOne,
  ClientAboutSectionTwo,
  ClientAboutSectionThree,
  Footer,
} from "@/components";

import { useAuthContext } from "@/contexts";

// todo: create head wrapper
export default function Home() {
  const { isAuthenticated, user, login, isLoading, logout } = useAuthContext();

  return (
    <>
      <Head>
        <title>TechLance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ClientHero />
        <ClientRecommendations />
        <ClientHomeCategories />
        <ClientAboutSectionOne />
        <ClientAboutSectionTwo />
        <ClientAboutSectionThree />
      </main>

      <Footer />
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {},
  };
}
