import React from "react";
import Head from "next/head";
import useSWR, { mutate } from "swr";

import {
  ClientHero,
  ClientServiceCategories,
  ClientRecommendations,
  ClientAboutSectionOne,
  ClientAboutSectionTwo,
  ClientAboutSectionThree,
  Footer,
} from "@/components";

import { useAuthContext } from "@/contexts";

export default function Home() {
  const { isAuthenticated, user, login, isLoading, logout } = useAuthContext();

  // todo: configure swr
  // const { data: { data: pages } = {}, isValidating } = useSWR(
  //   isAuthenticated ? false : "/pages",
  //   axiosClient.get
  // );

  return (
    <>
      <Head>
        <title>TechLance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ClientHero />
        <ClientRecommendations />
        <ClientServiceCategories />
        <ClientAboutSectionOne />
        <ClientAboutSectionTwo />
        <ClientAboutSectionThree />
      </main>

      <Footer />
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {},
  };
}
