import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import { BusinessHero, BusinessFeatures, Contact, Footer } from "@/components";

import { useAuthContext } from "@/contexts";
import { URL_CONSTANTS } from "@/constants";

export default function Business() {
  const router = useRouter();
  const { isTokenPresent } = useAuthContext();

  if (!isTokenPresent) {
    router.push(URL_CONSTANTS.BUSINESS.AUTH.LOGIN);
  }

  return (
    <>
      <Head>
        <title>TechLance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <BusinessHero />
        <BusinessFeatures />
        <Contact />
      </main>

      <Footer />
    </>
  );
}
